FROM nginx:1.29.5-alpine-slim

LABEL org.opencontainers.image.version="1.29.5" \
    org.opencontainers.image.authors="DevOps Navigator <switchtodevops@gmail.com>" \
    org.opencontainers.image.description="Demo Web Server" \
    org.opencontainers.image.build-date="2026-02-15" \
    org.opencontainers.image.source="https://github.com/DevOps-Navigator/nginx-image" \
    org.opencontainers.image.documentation="https://github.com/DevOps-Navigator/nginx-image/blob/main/README.md" \
    org.opencontainers.image.vendor="DevOps Navigator" \
    org.opencontainers.image.license="MIT" \
    org.opencontainers.image.copyright="Copyright 2026 DevOps Navigator" \
    org.opencontainers.image.url="https://github.com/devops-team/nginx-image" \
    org.opencontainers.image.title="DevOps Navigator" \
    org.opencontainers.image.description="Demo Web Server"

COPY index.html /usr/share/nginx/html